name: Trigger Databricks Job and Fail PR on Failure

on:
  pull_request:
    branches:
      - main  # Trigger on pull request to the main branch

jobs:
  trigger-databricks-job:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Checkout the repository code to the runner

    - name: Install curl and jq
      run: |
        sudo apt-get install curl jq  # Install jq to parse the response from the API

    - name: Trigger Databricks Job
      id: trigger_databricks
      run: |
        response=$(curl -X POST https://e2-demo-field-eng.cloud.databricks.com/api/2.1/jobs/run-now \
          -H "Authorization: Bearer ${{ secrets.DATABRICKS_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{
                "job_id": "${{ secrets.DATABRICKS_JOB_ID }}"
              }')
        
        # Extract the run_id from the response to track the job status
        run_id=$(echo $response | jq -r '.run_id')
        
        # Check if run_id is returned (if not, the job triggering failed)
        if [[ "$run_id" == "null" ]]; then
          echo "Databricks job failed to trigger. Aborting the PR.";
          exit 1;  # Fail the job and pull request
        fi

        # Wait for the job to finish and get the status (this might take some time)
        status_response=$(curl -X GET https://e2-demo-field-eng.cloud.databricks.com/api/2.1/jobs/runs/get \
          -H "Authorization: Bearer ${{ secrets.DATABRICKS_TOKEN }}" \
          -d "run_id=$run_id")
        
        # Extract the job status
        status=$(echo $status_response | jq -r '.state.result_state')

        # Check the job status, if it's failed, we fail the GitHub Actions workflow
        if [[ "$status" == "FAILED" ]]; then
          echo "Databricks job failed. Failing the PR.";
          exit 1;  # Fail the GitHub Action and thus the PR
        elif [[ "$status" != "SUCCESS" ]]; then
          echo "Databricks job did not complete successfully yet. Please check the job status in Databricks.";
          exit 1;  # Fail the PR if the status is unknown
        fi

    - name: Success
      if: success()
      run: |
        echo "Databricks job succeeded! PR passes."
